name: photo_lab
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.13+13



environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # for API calls
  dio: ^4.0.6

  #  local storage
  shared_preferences: ^2.0.15

  # A package that allows you to use the native file explorer to pick single or multiple files, with extensions filtering support.
  file_picker: ^5.3.0

  # Lottie is a mobile library for Android and iOS that parses Adobe After Effects animations exported as json with Bodymovin and renders them natively on mobile!
  lottie: 1.4.2

  # The Stripe Flutter SDK allows you to build delightful payment experiences in your native Android and iOS apps using Flutter.
  flutter_stripe: ^5.0.0

  # Provides internationalization and localization facilities, including message translation, plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.18.0

  #  A flutter package to select a country from a list of countries.
  country_picker: ^2.0.16

  #  A Flutter plugin for iOS and Android for picking images from the image library, and taking new pictures with the camera.
  image_picker: ^0.8.6

  #  A flutter plugin for accessing Dropbox.
  dropbox_client: ^1.0.0

  #  A Flutter plugin for finding commonly used locations on the filesystem.
  path_provider: ^2.0.11

  #  A Flutter plugin for launching a URL.
  url_launcher: ^6.1.7

  #  Flutter plugin to detect when app goes to background or foreground.
  flutter_fgbg: ^0.2.2

  # A cross platform plugin for displaying local notifications.
  flutter_local_notifications: ^15.0.1

  # to manage state
  provider: ^6.0.1

  #  for notification
  onesignal_flutter: ^3.5.0

  #  to open mart in webview
  webview_flutter: ^4.0.7

  #  for taking permissions
  permission_handler: ^10.2.0

  #  to send otp on user phone number
  twilio_flutter: ^0.0.9

  #  payment method
  instamojo: ^1.0.0+2

  #  to cache network image so that they are not loaded again and again
  cached_network_image: ^3.2.1

  #  for firebase
  firebase_core_platform_interface: 4.8.0
  firebase_auth_platform_interface: 6.15.1
  firebase_core: 2.13.0
  firebase_auth: 4.6.1
  cloud_firestore: 4.7.1
  firebase_storage: 11.2.1
  firebase_messaging: 14.6.1

  #  to sign in using google
  google_sign_in: 6.1.0

  #  to display google map for booking
  google_maps_flutter: ^2.2.6

  #  a fancy loading indicator
  pull_to_refresh: ^2.0.0

  #  to show payment card details on card
  flutter_credit_card: ^3.0.4

  #  to input mobile number otp
  pin_code_fields: ^7.4.0

  #  to show floating message of success and errors
  fluttertoast: ^8.1.1

  #
  flutter_rating_bar: ^4.0.1

  #
  carousel_slider: ^4.2.1

  #  we are only using SfCartesianChart class from below package, so i thing we need to add that class as module
  syncfusion_flutter_charts: 20.4.54

  # to display svg icons
  flutter_svg: ^2.0.7

  #  Below package is used to show count on icons
  badges: ^3.1.2


dev_dependencies:
  flutter_launcher_icons: "^0.11.0"
  flutter_test:
    sdk: flutter
  place_picker:
    path: place_picker-0.10.0_upd

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/photo_lab_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/



  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/fonts/albert_sans/AlbertSans-Black.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-BlackItalic.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-Bold.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-BoldItalic.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-ExtraBold.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-ExtraLight.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-ExtraLightItalic.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-Italic.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-Light.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-LightItalic.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-Medium.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-MediumItalic.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-Regular.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-SemiBold.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-SemiBoldItalic.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-Thin.ttf
        - asset: assets/fonts/albert_sans/AlbertSans-ThinItalic.ttf


 